services:
  frontend-beta:
    image: cr.yandex/${YCR_REGISTRY_ID}/bottlecode-frontend:beta
    env_file:
      - .env.beta
    expose:
      - "80"
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.redirect-https.redirectScheme.scheme=https
      - traefik.http.middlewares.redirect-https.redirectScheme.permanent=true
      - traefik.http.routers.frontend-beta.rule=Host(`beta.bottlecode.app`)
      - traefik.http.routers.frontend-beta.entrypoints=websecure
      - traefik.http.routers.frontend-beta.tls.certresolver=letsencrypt
      - traefik.http.services.frontend-beta.loadbalancer.server.port=80
    networks:
      - proxy

  frontend-stable:
    image: cr.yandex/${YCR_REGISTRY_ID}/bottlecode-frontend:latest
    env_file:
      - .env.stable
    expose:
      - "80"
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.redirect-https.redirectScheme.scheme=https
      - traefik.http.middlewares.redirect-https.redirectScheme.permanent=true
      - traefik.http.routers.frontend-stable.rule=Host(`bottlecode.app`)
      - traefik.http.routers.frontend-stable.entrypoints=websecure
      - traefik.http.routers.frontend-stable.tls.certresolver=letsencrypt
      - traefik.http.services.frontend-stable.loadbalancer.server.port=80
    networks:
      - proxy

networks:
  proxy:
    external: true
